### ISSUE TITLE
map-get() just fails with a TypeError (Webpack context)

### ISSUE THREAD

**Issue by oatymart** [Scrum/postcss-map-get#14]
Can I get some help? I am trying to use `postcss-map-get` in a Storybook instance via Webpack. Even with the simplest map definition and `map-get`, it fails to build.

My test CSS:
```css
$mymap: (
    mycolor: #c0ffee
);
p {
    color: map-get($mymap, mycolor); /* <-- _colors.css:44 */
}
```

My `postcss.config.js`:
```js
const plugins = {
    'postcss-import': {},
    'postcss-strip-inline-comments': {},
    'postcss-advanced-variables': {},
    'postcss-map-get': {},
    'postcss-preset-env': {
        stage: 1
    }
};

if (process.env.NODE_ENV === 'production') {
    plugins.cssnano = {};
}

module.exports = {
    syntax: 'postcss-scss',
    plugins
};
```
The above plugins were working before I added `postcss-map-get`. I have tried changing the order of the plugins.

Webpack error:
```
ERROR in ./packages/identity/scss/main.css (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??postcss!./node_modules/postcss-loader/src??postcss!./packages/identity/scss/main.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: value.match is not a function or its return value is not iterable
    at packages/identity/scss/abstracts/_colors.css:44:5
    at _default (node_modules/postcss-map-get/lib/str-get-content.js:1:477)
    at valResolve (node_modules/postcss-map-get/lib/index.js:2:410)
    at nodes.walkDecls.decl (node_modules/postcss-map-get/lib/index.js:2:626)
    at node_modules/postcss/lib/container.js:190:18
    at node_modules/postcss/lib/container.js:135:18
    at Rule.each (node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (node_modules/postcss/lib/container.js:131:17)
    at node_modules/postcss/lib/container.js:148:24
    at Root.each (node_modules/postcss/lib/container.js:101:16)
    at Root.walk (node_modules/postcss/lib/container.js:131:17)
    at Root.walkDecls (node_modules/postcss/lib/container.js:188:19)
    at nodes (node_modules/postcss-map-get/lib/index.js:2:547)
    at LazyResult.run (node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (node_modules/postcss/lib/lazy-result.js:208:26)
    at node_modules/postcss/lib/lazy-result.js:213:17
    at <anonymous>
 @ ./packages/identity/scss/main.css 2:14-210 21:1-42:3 22:19-215
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

**Comment by Scrum** [comment]
@oatymart Hi yes of course

If you provide a link on the github to reproduce this error, most likely we will be able to fix it more quickly.

Thank.

**Comment by oatymart** [comment]
Sorry but it's inside a private repo, I can't link the whole code.

Do you have any suggestions how I can debug myself?

**Comment by Scrum** [comment]
It will take me some time to reproduce this error according to your criteria, stay on the line))

**Comment by Scrum** [comment]
I created an [example](https://github.com/inside-demo/postcss-map-get-webpack-demo) in which compilation is successful.

Please make the necessary changes to achieve your error.

**Comment by oatymart** [comment]
Thank you so much for taking the time to investigate and set up this example project! That is some heroic support work right there.

Sadly I am not able to get the project to work - even after adding a `webpack-dev-server` and `index.html` and `style-loader`, I am not able to display the intended color in the browser.

However, there is no error about the `map-get` use, so maybe it works and I still need to learn what is going on.

**Comment by Scrum** [comment]
I think it's worth trying to look at the inspector and analyze this selector for invalid properties, maybe you should look into the bundle itself and see the compilation result, maybe there has not been a complete transformation.

Ideally, you must of course know your goals in order to think about the correctness of the solution and approach.
