### ISSUE TITLE
Error: [object Object] is not a PostCSS plugin

### ISSUE THREAD

**Issue by giovannipiller** [Scrum/postcss-map-get#18]
I've upgraded PostCSS from v0.2.5 to **v0.2.7**, and this error appeared in my console.
I've tried reverting [this commit](https://github.com/Scrum/postcss-map-get/commit/bb225c59098e4d931f9baa8802859ffdc772adc2), and everything started working as normal.

```
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/Users/myuser/bitbucket/myproject/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/Users/myuser/bitbucket/myproject/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/Users/myuser/bitbucket/myproject/node_modules/postcss/lib/postcss.js:55:10)
    at /Users/myuser/bitbucket/myproject/node_modules/postcss-loader/src/index.js:140:12
```

## Versions:
- Babel 7.4.4
- Webpack 4.41.0
- postcss-loader 3.0.0

**Comment by marcalexiei** [comment]
Issue has been fixed with 0.2.8. 

Thanks for the report and the investigation!
